---
- name: Install Python 3.8 and Set Up Virtual Environment
  hosts: mylocalpc
  become: yes

  tasks:
    - name: Add deadsnakes PPA for Python 3.8
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Python 3.8
      apt:
        name: python3.8
        state: present

    - name: Install Python 3.8 virtual environment package
      apt:
        name: python3.8-venv
        state: present

    - name: Create a directory for Python packages
      file:
        path: /opt/fde/gx_38
        state: directory

    - name: Copy requirements.txt to the remote server
      copy:
        src: /home/yogi/DE/ansible/requirements.txt
        dest: /opt/fde/gx_38/requirements.txt

    - name: Create a Python 3.8 virtual environment
      command: python3.8 -m venv /opt/fde/gx_38/.venv
      args:
        creates: /opt/fde/gx_38/.venv

    - name: Install Python packages in the virtual environment
      command: /opt/fde/gx_38/.venv/bin/pip install -r /opt/fde/gx_38/requirements.txt
